name: Merge
on:
    pull_request:
        branches:
            - master
jobs:
    merge:
        needs: build
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
            - name: "Install"
              uses: ./.github/actions/install
              with:
                node-version: ${{ env.PRIMARY_NODE_VERSION }}
            - uses: fastify/github-action-merge-dependabot@v3
