name: Publish
on:
    pull_request:
        types:
            - closed

jobs:
    publish:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: "Install"
              uses: ./.github/actions/install
              with:
                  node-version: ${{ env.PRIMARY_NODE_VERSION }}
                  registry-url: https://registry.npmjs.org

            - name: "Git HEAD"
              id: head
              shell: bash
              run: |
                    echo "::set-output name=sha::$(git rev-parse HEAD)"

            - name: "Version & publish"
              if: github.sha == steps.head.outputs.sha
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor}}@users.noreply.github.com"
                  npx lerna version --conventional-commits --conventional-graduate --yes
                  npx lerna publish from-git --no-verify-access --yes
